INSERT INTO book_master (BookNo, Title, Author1, Author2, Author3, Edition, Publisher, Status, Pages, Remark, Rating)
VALUES
(1, 'The Great Gatsby', 'F. Scott Fitzgerald', NULL, NULL, '1st', 'Scribner', 'Available', 180, 'Classic novel', 4.7),
(2, 'To Kill a Mockingbird', 'Harper Lee', NULL, NULL, '1st', 'J.B. Lippincott & Co.', 'Issued', 281, 'Pulitzer Prize winner', 4.8),
(3, '1984', 'George Orwell', NULL, NULL, '1st', 'Secker & Warburg', 'Available', 328, 'Dystopian novel', 4.6),
(4, 'The Catcher in the Rye', 'J.D. Salinger', NULL, NULL, '1st', 'Little, Brown and Company', 'Issued', 277, 'Classic literature', 4.5),
(5, 'Moby-Dick', 'Herman Melville', NULL, NULL, '1st', 'Harper & Brothers', 'Available', 635, 'Adventure novel', 4.3),
(6, 'Pride and Prejudice', 'Jane Austen', NULL, NULL, '1st', 'T. Egerton', 'Available', 432, 'Romantic novel', 4.9),
(7, 'The Hobbit', 'J.R.R. Tolkien', NULL, NULL, '1st', 'George Allen & Unwin', 'Issued', 310, 'Fantasy novel', 4.8),
(8, 'War and Peace', 'Leo Tolstoy', NULL, NULL, '1st', 'The Russian Messenger', 'Available', 1225, 'Historical novel', 4.7),
(9, 'Crime and Punishment', 'Fyodor Dostoevsky', NULL, NULL, '1st', 'The Russian Messenger', 'Issued', 671, 'Psychological novel', 4.6),
(10, 'The Odyssey', 'Homer', NULL, NULL, 'Ancient', 'Various', 'Available', 500, 'Epic poem', 4.9),
(11, 'The Iliad', 'Homer', NULL, NULL, 'Ancient', 'Various', 'Available', 600, 'Greek mythology', 4.8),
(12, 'Brave New World', 'Aldous Huxley', NULL, NULL, '1st', 'Chatto & Windus', 'Available', 311, 'Science fiction', 4.5),
(13, 'The Divine Comedy', 'Dante Alighieri', NULL, NULL, 'Ancient', 'Various', 'Available', 798, 'Epic poem', 4.9),
(14, 'Frankenstein', 'Mary Shelley', NULL, NULL, '1st', 'Lackington, Hughes, Harding, Mavor & Jones', 'Issued', 280, 'Gothic fiction', 4.7),
(15, 'Don Quixote', 'Miguel de Cervantes', NULL, NULL, '1st', 'Francisco de Robles', 'Available', 863, 'Satirical novel', 4.6),
(16, 'Jane Eyre', 'Charlotte Brontë', NULL, NULL, '1st', 'Smith, Elder & Co.', 'Available', 500, 'Classic literature', 4.8),
(17, 'Wuthering Heights', 'Emily Brontë', NULL, NULL, '1st', 'Thomas Cautley Newby', 'Issued', 416, 'Romantic novel', 4.7),
(18, 'Dracula', 'Bram Stoker', NULL, NULL, '1st', 'Archibald Constable and Company', 'Available', 418, 'Horror novel', 4.5),
(19, 'The Picture of Dorian Gray', 'Oscar Wilde', NULL, NULL, '1st', 'Ward, Lock & Co.', 'Available', 320, 'Philosophical novel', 4.6),
(20, 'The Metamorphosis', 'Franz Kafka', NULL, NULL, '1st', 'Kurt Wolff Verlag', 'Available', 201, 'Surreal fiction', 4.4),
(21, 'Les Misérables', 'Victor Hugo', NULL, NULL, '1st', 'A. Lacroix, Verboeckhoven & Cie.', 'Available', 1463, 'Historical novel', 4.9),
(22, 'The Count of Monte Cristo', 'Alexandre Dumas', NULL, NULL, '1st', 'Pétion', 'Issued', 1276, 'Adventure novel', 4.8),
(23, 'Anna Karenina', 'Leo Tolstoy', NULL, NULL, '1st', 'The Russian Messenger', 'Available', 864, 'Realist novel', 4.7),
(24, 'The Brothers Karamazov', 'Fyodor Dostoevsky', NULL, NULL, '1st', 'The Russian Messenger', 'Available', 796, 'Philosophical novel', 4.8),
(25, 'The Old Man and the Sea', 'Ernest Hemingway', NULL, NULL, '1st', 'Charles Scribner\'s Sons', 'Issued', 127, 'Short novel', 4.6);
