INSERT INTO book_master (BookNo, Title, Author1, Author2, Author3, Edition, Publisher, Status, Pages, Remark, Rating) VALUES
(1, 'The Lord of the Rings', 'J.R.R. Tolkien', NULL, NULL, 'Extended', 'Allen & Unwin', 'Available', 1216, 'Classic Fantasy', 4.8),
(2, 'Pride and Prejudice', 'Jane Austen', NULL, NULL, 'Original', 'T. Egerton', 'Available', 432, 'Romantic Novel', 4.5),
(3, 'Dune', 'Frank Herbert', NULL, NULL, 'First', 'Chilton Books', 'Borrowed', 896, 'Sci-Fi Epic', 4.7),
(4, 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', NULL, NULL, 'Revised', 'Pan Books', 'Available', 224, 'Sci-Fi Comedy', 4.6),
(5, '1984', 'George Orwell', NULL, NULL, 'First', 'Secker & Warburg', 'Available', 328, 'Dystopian', 4.4),
(6, 'To Kill a Mockingbird', 'Harper Lee', NULL, NULL, 'First', 'J. B. Lippincott & Co.', 'Borrowed', 324, 'Classic Literature', 4.9),
(7, 'The Great Gatsby', 'F. Scott Fitzgerald', NULL, NULL, 'First', 'Charles Scribner''s Sons', 'Available', 180, 'American Classic', 4.3),
(8, 'Moby-Dick', 'Herman Melville', NULL, NULL, 'First', 'Richard Bentley', 'Available', 625, 'American Epic', 4.2),
(9, 'One Hundred Years of Solitude', 'Gabriel García Márquez', NULL, NULL, 'First', 'Editorial Sudamericana', 'Available', 417, 'Magical Realism', 4.7),
(10, 'Brave New World', 'Aldous Huxley', NULL, NULL, 'First', 'Chatto & Windus', 'Borrowed', 268, 'Dystopian', 4.1),
(11, 'Foundation', 'Isaac Asimov', NULL, NULL, 'First', 'Gnome Press', 'Available', 255, 'Sci-Fi Series', 4.6),
(12, 'The Catcher in the Rye', 'J.D. Salinger', NULL, NULL, 'First', 'Little, Brown and Company', 'Available', 277, 'Coming-of-Age', 4.0),
(13, 'Crime and Punishment', 'Fyodor Dostoevsky', NULL, NULL, 'First', 'The Russian Messenger', 'Available', 671, 'Psychological Thriller', 4.8),
(14, 'Jane Eyre', 'Charlotte Brontë', NULL, NULL, 'First', 'Smith, Elder & Co.', 'Borrowed', 532, 'Gothic Romance', 4.5),
(15, 'The Hobbit', 'J.R.R. Tolkien', NULL, NULL, 'First', 'Allen & Unwin', 'Available', 310, 'Fantasy Adventure', 4.7),
(16, 'The Color Purple', 'Alice Walker', NULL, NULL, 'First', 'Harcourt Brace Jovanovich', 'Available', 245, 'Epistolary Novel', 4.6),
(17, 'Wuthering Heights', 'Emily Brontë', NULL, NULL, 'First', 'T. C. Newby', 'Available', 342, 'Gothic Romance', 4.3),
(18, 'Slaughterhouse-Five', 'Kurt Vonnegut', NULL, NULL, 'First', 'Delacorte Press', 'Borrowed', 275, 'Anti-War Novel', 4.2),
(19, 'The Handmaid''s Tale', 'Margaret Atwood', NULL, NULL, 'First', 'McClelland and Stewart', 'Available', 311, 'Dystopian', 4.8),
(20, 'The Book Thief', 'Markus Zusak', NULL, NULL, 'First', 'Alfred A. Knopf', 'Available', 576, 'Historical Fiction', 4.9),
(21, 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', NULL, NULL, 'First', 'Bloomsbury', 'Available', 309, 'Fantasy', 4.7),
(22, 'The Da Vinci Code', 'Dan Brown', NULL, NULL, 'First', 'Doubleday', 'Borrowed', 454, 'Mystery Thriller', 4.1),
(23, 'Life of Pi', 'Yann Martel', NULL, NULL, 'First', 'Knopf Canada', 'Available', 319, 'Adventure Fiction', 4.5),
(24, 'The Girl with the Dragon Tattoo', 'Stieg Larsson', NULL, NULL, 'First', 'Norstedts Förlag', 'Available', 464, 'Crime Thriller', 4.6),
(25, 'The Hunger Games', 'Suzanne Collins', NULL, NULL, 'First', 'Scholastic Press', 'Borrowed', 374, 'Dystopian', 4.4),
(26, 'Little Women', 'Louisa May Alcott', NULL, NULL, 'First', 'Roberts Brothers', 'Available', 541, 'Coming-of-Age', 4.8),
(27, 'The Road', 'Cormac McCarthy', NULL, NULL, 'First', 'Alfred A. Knopf', 'Available', 241, 'Post-Apocalyptic', 4.3),
(28, 'Catch-22', 'Joseph Heller', NULL, NULL, 'First', 'Simon & Schuster', 'Available', 453, 'Satirical Novel', 4.2),
(29, 'A Game of Thrones', 'George R.R. Martin', NULL, NULL, 'First', 'Bantam Books', 'Borrowed', 694, 'Fantasy Epic', 4.9),
(30, 'The Shadow of the Wind', 'Carlos Ruiz Zafón', NULL, NULL, 'First', 'Planeta', 'Available', 561, 'Historical Mystery', 4.7),
(31, 'The Alchemist', 'Paulo Coelho', NULL, NULL, 'First', 'HarperCollins', 'Available', 197, 'Philosophical Novel', 4.6),
(32, 'The Kite Runner', 'Khaled Hosseini', NULL, NULL, 'First', 'Riverhead Books', 'Borrowed', 371, 'Historical Fiction', 4.5),
(33, 'The Time Traveler''s Wife', 'Audrey Niffenegger', NULL, NULL, 'First', 'MacAdam/Cage', 'Available', 519, 'Romance', 4.4),
(34, 'Shantaram', 'Gregory David Roberts', NULL, NULL, 'First', 'Scribe Publications', 'Available', 936, 'Autobiographical Novel', 4.8),
(35, 'The Pillars of the Earth', 'Ken Follett', NULL, NULL, 'First', 'William Morrow and Company', 'Borrowed', 973, 'Historical Novel', 4.3),
(36, 'The Name of the Wind', 'Patrick Rothfuss', NULL, NULL, 'First', 'DAW Books', 'Available', 662, 'Fantasy', 4.2),
(37, 'The Martian', 'Andy Weir', NULL, NULL, 'First', 'Crown Publishing Group', 'Available', 384, 'Sci-Fi', 4.9),
(38, 'Gone Girl', 'Gillian Flynn', NULL, NULL, 'First', 'Crown Publishing Group', 'Borrowed', 422, 'Psychological Thriller', 4.7),
(39, 'The Help', 'Kathryn Stockett', NULL, NULL, 'First', 'Amy Einhorn Books', 'Available', 444, 'Historical Fiction', 4.6),
(40, 'The Night Circus', 'Erin Morgenstern', NULL, NULL, 'First', 'Doubleday', 'Available', 387, 'Fantasy', 4.5);





